name: Build ZMK Firmware

on: 
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
  
  create_release:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download firmware artifacts
        uses: actions/download-artifact@v4
        with:
          name: firmware

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Create Release with firmware
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.date.outputs.date }}-${{ github.sha }}
          name: Firmware ${{ steps.date.outputs.date }}
          body: Build from commit ${{ github.sha }}
          files: '*.uf2'
